create table clientes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome varchar (100) not null,
    email varchar(100) unique
);

create table produtos (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome varchar(100) not null,
    preco number(10,2) not null check (preco >= 0),
    tipo varchar(50) not null
);

create table pedidos (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    produto_id NUMBER NOT NULL,
    CONSTRAINT fk_cliente_id FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_produto_id FOREIGN KEY (produto_id) REFERENCES produtos(id),
    status varchar(20) not null check (status in ('Aberto', 'Finalizado', 'Cancelado'))
);



insert into clientes (nome, email) values ('Phelipe', 'phelipe@senac.br');

insert into clientes (nome, email) values ('Samuel', 'samuelpetista@senac.br');

insert into clientes (nome, email) values ('Robson', 'robsoncorinthians@senac.br');

insert into produtos (nome, preco, tipo) values ('Playstation 5', 10000 ,'Consolo');

insert into produtos (nome, preco, tipo) values ('Samsung J5 Prime', 300 ,'Celular');

insert into produtos (nome, preco, tipo) values ('Lubrificante', 3.50 ,'Lubrificante');

insert into pedidos (CLIENTE_ID, PRODUTO_ID, status) values (1, 2, 'Cancelado');

insert into pedidos (CLIENTE_ID, PRODUTO_ID, status) values (2, 1, 'Cancelado');

insert into pedidos (CLIENTE_ID, PRODUTO_ID, status) values (3, 3, 'Cancelado');

delete from pedidos where status = 'Cancelado';


create table clientes2(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome varchar (100) not null,
    email varchar(100) not null
);


MERGE INTO clientes c
USING clientes2 c2
ON (c.id_cliente = c2.id_cliente)
WHEN MATCHED THEN
  UPDATE SET
    c.nome = c2.nome,
    c.email = c2.email
WHEN NOT MATCHED THEN
  INSERT (id_cliente, nome, email)
  VALUES (c2.id_cliente, c2.nome, c2.email);

select * from clientes;

select * from produtos;

select * from pedidos;